import { Component, OnInit } from '@angular/core';
import { delay, catchError, of } from 'rxjs';
import { Modulo } from 'src/app/models/Modulo';
import { SenacCoin } from 'src/app/models/SenacCoin';
import { SenacCoinMovimentacao } from 'src/app/models/SenacCoinMovimentacao';
import { UnidadeCurricular } from 'src/app/models/UnidadeCurricular';
import { AuthGuardService } from 'src/app/services/auth-guard.service';
import { ModuloService } from 'src/app/services/modulo.service';
import { UnidadeCurricularService } from 'src/app/services/unidade-curricular.service';
import { ErrorService } from 'src/app/shared/alerts/error-dialog/error-dialog.service';

@Component({
  selector: 'app-trilha-curso',
  templateUrl: './usuario-trilha-curso.component.html',
  styleUrls: ['./usuario-trilha-curso.component.css']
})
export class UsuarioTrilhaCursoComponent implements OnInit {

  senacCoins: SenacCoin;
  loading: boolean = true;
  senacCoinMovimentacoes: SenacCoinMovimentacao[];
  idEstudanteUsuarioLogado: number;
  modulos: Modulo[];
  modulosTotal: any[];

  constructor(
    private authGuardService: AuthGuardService,
    private unidadeCurricularService: UnidadeCurricularService,
    private errorService: ErrorService,
    private moduloService: ModuloService,
  ) { }

  ngOnInit(): void {

    this.idEstudanteUsuarioLogado = this.authGuardService.getIdEstudanteUsuarioLogado();

    this.ObterModulos();

  }

  ObterModulos = () => {
    this.moduloService.ObterModulosPorEstudanteId(this.idEstudanteUsuarioLogado).pipe(
      catchError((error) => {
        this.errorService.onError('Erro ao carregar unidades curriculares.');
        return of([]);
      })
    ).subscribe((resultadoUnidadesCurriculares) => {
      this.modulos = resultadoUnidadesCurriculares;
      console.log(this.idEstudanteUsuarioLogado)
      console.log(this.modulos)
    });

    this.modulosTotal = [{
      "id": 1,
      "descricao": "Módulo 1",
      "cargaHoraria": 400,
      "ofertaId": 1,
      "oferta": null,
      "unidadesCurriculares": [
        {
          "id": 1,
          "codigo": "12487 1.1",
          "imagem": null,
          "nome": "Introdução à Programação",
          "nomeCurto": "INTRODUÇÃO À PROGRAMAÇÃO",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 1,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 2,
          "codigo": "12487 1.2",
          "imagem": null,
          "nome": "Arquitetura de Computadores em Sistemas de Informação",
          "nomeCurto": "ARQUITETURA DE COMPUTADORES EM SI",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 2,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 3,
          "codigo": "12487 1.3",
          "imagem": null,
          "nome": "Raciocínio Lógico e Matemático",
          "nomeCurto": "RACIOCÍNIO LÓGICO E MATEMÁTICO",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 3,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 4,
          "codigo": "12487 1.4",
          "imagem": null,
          "nome": "Introdução a Redes de Computadores",
          "nomeCurto": "INTRODUÇÃO A REDES E COMPUTADORES",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 4,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 5,
          "codigo": "12487 1.5",
          "imagem": null,
          "nome": "Engenharia de Software I",
          "nomeCurto": "ENGENHARIA DE SOFTWARE I",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 5,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 6,
          "codigo": "12487 1.6",
          "imagem": null,
          "nome": "Engenharia de Usabilidade",
          "nomeCurto": "ENGENHARIA DE USABILIDADE",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 6,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 7,
          "codigo": "12487 1.7",
          "imagem": null,
          "nome": "Tecnologia Web I",
          "nomeCurto": "TECNOLOGIA WEB I",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 7,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 8,
          "codigo": "12487 1.8",
          "imagem": null,
          "nome": "Empreendedorismo e Inovação",
          "nomeCurto": "EMPREENDEDORISMO E INOVAÇÃO",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 8,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 9,
          "codigo": "12487 1.9",
          "imagem": null,
          "nome": "Projeto Integrador I: ARTEFATOS E PROTÓTIPOS",
          "nomeCurto": "PROJETO INTEGRADOR: ARTEFATOS E PROTÓTIPOS",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 9,
          "status": 1,
          "moduloId": null,
          "modulo": null,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        }
      ]
    },
  
    {
      "id": 2,
      "descricao": "Módulo 2",
      "cargaHoraria": 400,
      "ofertaId": 1,
      "oferta": null,
      "unidadesCurriculares": [
        {
          "id": 10,
          "codigo": "12487 2.1",
          "imagem": null,
          "nome": "Banco de Dados I",
          "nomeCurto": "BANCO DE DADOS I",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 10,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 11,
          "codigo": "12487 2.2",
          "imagem": null,
          "nome": "Engenharia de Software II",
          "nomeCurto": "ENGENHARIA DE SOFTWARE II",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 11,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 12,
          "codigo": "12487 2.3",
          "imagem": null,
          "nome": "Design de Interfaces",
          "nomeCurto": "DESIGN DE INTERFACES",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 12,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 13,
          "codigo": "12487 2.4",
          "imagem": null,
          "nome": "Estrutura de Dados",
          "nomeCurto": "ESTRUTURA DE DADOS",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 13,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 14,
          "codigo": "12487 2.5",
          "imagem": null,
          "nome": "Tecnologia Web II",
          "nomeCurto": "TECNOLOGIA WEB II",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 14,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 15,
          "codigo": "12487 2.6",
          "imagem": null,
          "nome": "Programção I",
          "nomeCurto": "PROGRAMACÃO I",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 15,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 16,
          "codigo": "12487 2.7",
          "imagem": null,
          "nome": "Projeto Integrador II: MODELOS DO PROJETO PARA DESENVOLVIMENTO DE SISTEMAS",
          "nomeCurto": "PROJETO INTEGRADOR: MODELOS DO PROJETO",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 16,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        }
      ]
    },
  
    {
      "id": 3,
      "descricao": "Módulo 3",
      "cargaHoraria": 400,
      "ofertaId": 1,
      "oferta": null,
      "unidadesCurriculares": [
        {
          "id": 17,
          "codigo": "12487 3.1",
          "imagem": null,
          "nome": "Sistemas Operacionais",
          "nomeCurto": "SISTEMAS OPERACIONAIS",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 17,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 18,
          "codigo": "12487 3.2",
          "imagem": null,
          "nome": "Banco de Dados II",
          "nomeCurto": "BANCO DE DADOS II",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 18,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 19,
          "codigo": "12487 3.3",
          "imagem": null,
          "nome": "Métricas e Auditoria de Software",
          "nomeCurto": "METRICAS E AUDITORIA DE SOFTWARE",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 19,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 20,
          "codigo": "12487 3.4",
          "imagem": null,
          "nome": "Probabilidade e Estatística",
          "nomeCurto": "PROBABILIDADE E ESTATÍSTICA",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 20,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 21,
          "codigo": "12487 3.5",
          "imagem": null,
          "nome": "Tecnologia Web III",
          "nomeCurto": "TECNOLOGIA WEB III",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 21,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 22,
          "codigo": "12487 3.6",
          "imagem": null,
          "nome": "Segurança da Informação",
          "nomeCurto": "SEGURANÇA DA INFORMAÇÃO",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 22,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 23,
          "codigo": "12487 3.7",
          "imagem": null,
          "nome": "Programação II",
          "nomeCurto": "PROGRAMAÇÃO II",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 23,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 24,
          "codigo": "12487 3.8",
          "imagem": null,
          "nome": "Projeto Integrador III: APLICAÇÃO SEGURA E AUDITADA",
          "nomeCurto": "PROJETO INTEGRADOR: APLICAÇÃO SEGURA E AUDITADA",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 24,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        }
      ]
    },

    {
      "id": 4,
      "descricao": "Módulo 4",
      "cargaHoraria": 400,
      "ofertaId": 1,
      "oferta": null,
      "unidadesCurriculares": [
        {
          "id": 25,
          "codigo": "12487 4.1",
          "imagem": null,
          "nome": "Testes de Software",
          "nomeCurto": "Testes de Software",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 25,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 26,
          "codigo": "12487 4.2",
          "imagem": null,
          "nome": "Programação para Dispositivos Móveis",
          "nomeCurto": "Programação para Dispositivos Móveis",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 26,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 27,
          "codigo": "12487 4.3",
          "imagem": null,
          "nome": "Programação Web I",
          "nomeCurto": "Programação Web I",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 27,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 28,
          "codigo": "12487 4.4",
          "imagem": null,
          "nome": "Computação em nuvem",
          "nomeCurto": "Computação em nuvem",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 28,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 29,
          "codigo": "12487 4.5",
          "imagem": null,
          "nome": "Gerência de Projetos em TI",
          "nomeCurto": "Gerência de Projetos em TI",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 29,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 30,
          "codigo": "12487 4.6",
          "imagem": null,
          "nome": "Português Instrumental",
          "nomeCurto": "Português Instrumental",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 30,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 31,
          "codigo": "12487 4.7",
          "imagem": null,
          "nome": "Projeto Integrador 4: Aplicação multiplataforma com identificação de falhas",
          "nomeCurto": "Projeto Integrador: Aplicação multiplataforma",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 30,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        }
      ]
    },

    {
      "id": 5,
      "descricao": "Módulo 5",
      "cargaHoraria": 400,
      "ofertaId": 1,
      "oferta": null,
      "unidadesCurriculares": [
        {
          "id": 32,
          "codigo": "12487 5.1",
          "imagem": null,
          "nome": "Programação Web II",
          "nomeCurto": "Programação Web II",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 32,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 33,
          "codigo": "12487 5.2",
          "imagem": null,
          "nome": "Gerenciamento Ágil de Projetos",
          "nomeCurto": "Gerenciamento Ágil de Projetos",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 33,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 35,
          "codigo": "12487 5.4",
          "imagem": null,
          "nome": "Gestão e Governança de TI",
          "nomeCurto": "Gestão e Governança de TI",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 35,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 36,
          "codigo": "12487 5.5",
          "imagem": null,
          "nome": "Ética e Legislação em TI",
          "nomeCurto": "Ética e Legislação em TI",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 36,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 37,
          "codigo": "12487 5.6",
          "imagem": null,
          "nome": "Tópicos Especiais em TI",
          "nomeCurto": "Tópicos Especiais em TI",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 37,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 38,
          "codigo": "12487 5.7",
          "imagem": null,
          "nome": "Diversidade Cultural e Direitos Humanos",
          "nomeCurto": "Diversidade Cultural e Direitos Humanos",
          "horas": 40,
          "numeroModulo": null,
          "ordem": 38,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        },
        {
          "id": 39,
          "codigo": "12487 5.8",
          "imagem": null,
          "nome": "Projeto Integrador 5: Aplicação Java Web em nuvem com gestão de projeto ágil",
          "nomeCurto": "Projeto Integrador: Aplicação Java Web em nuvem",
          "horas": 80,
          "numeroModulo": null,
          "ordem": 39,
          "status": null,
          "moduloId": null,
          "modulo": null,
          "statusCursado": 0,
          "competencias": null,
          "grupos": null,
          "bibliografias": null,
          "registroAvaliacao": null
        }
      ]
    }


  ]
}}
