export const cardsData = [
    {
      name: 'canetas',
      Modalname: 'canetas',
      price: '250',
      description: 'lorem ipsum dolor sit amet, consectetur adiporem ipsum dolor sit amet sit amet, consectetur adiporem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'lapis',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'caderno',
      Modalname: 'canetas',
      price: '500',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'borracha',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'borracha',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'borracha',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'borracha',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'borracha',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
    {
      name: 'borracha',
      Modalname: 'canetas',
      price: '150',
      description: 'lorem ipsum dolor sit amet, consectetur adip',
      img: '',
    },
  ];